version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "openshift/release"
        # don't automatically upgrade golang version here
  - package-ecosystem: "gomod"
    directory: "/"
    #allow:
    #  - dependency-name: "github.com/openshift/ocm-agent-operator"
    schedule:
      interval: 'daily'