version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/build"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "openshift/release"
        # don't automatically upgrade golang version here
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "weekly"
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      openshift:
        patterns:
          - "github.com/openshift/*"
      prometheus:
        patterns:
          - "github.com/prometheus/*"