// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/ocm-agent/pkg/ocm (interfaces: OCMClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
	v10 "github.com/openshift-online/ocm-sdk-go/servicelogs/v1"
)

// MockOCMClient is a mock of OCMClient interface.
type MockOCMClient struct {
	ctrl     *gomock.Controller
	recorder *MockOCMClientMockRecorder
}

// MockOCMClientMockRecorder is the mock recorder for MockOCMClient.
type MockOCMClientMockRecorder struct {
	mock *MockOCMClient
}

// NewMockOCMClient creates a new mock instance.
func NewMockOCMClient(ctrl *gomock.Controller) *MockOCMClient {
	mock := &MockOCMClient{ctrl: ctrl}
	mock.recorder = &MockOCMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCMClient) EXPECT() *MockOCMClientMockRecorder {
	return m.recorder
}

// GetCluster mocks base method.
func (m *MockOCMClient) GetCluster(arg0 string) (*v1.Cluster, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", arg0)
	ret0, _ := ret[0].(*v1.Cluster)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockOCMClientMockRecorder) GetCluster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockOCMClient)(nil).GetCluster), arg0)
}

// GetLimitedSupportReasons mocks base method.
func (m *MockOCMClient) GetLimitedSupportReasons(arg0 string) ([]*v1.LimitedSupportReason, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimitedSupportReasons", arg0)
	ret0, _ := ret[0].([]*v1.LimitedSupportReason)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimitedSupportReasons indicates an expected call of GetLimitedSupportReasons.
func (mr *MockOCMClientMockRecorder) GetLimitedSupportReasons(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimitedSupportReasons", reflect.TypeOf((*MockOCMClient)(nil).GetLimitedSupportReasons), arg0)
}

// GetUpgradePolicies mocks base method.
func (m *MockOCMClient) GetUpgradePolicies(arg0 string) ([]*v1.UpgradePolicy, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradePolicies", arg0)
	ret0, _ := ret[0].([]*v1.UpgradePolicy)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUpgradePolicies indicates an expected call of GetUpgradePolicies.
func (mr *MockOCMClientMockRecorder) GetUpgradePolicies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradePolicies", reflect.TypeOf((*MockOCMClient)(nil).GetUpgradePolicies), arg0)
}

// GetUpgradePolicy mocks base method.
func (m *MockOCMClient) GetUpgradePolicy(arg0, arg1 string) (*v1.UpgradePolicy, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradePolicy", arg0, arg1)
	ret0, _ := ret[0].(*v1.UpgradePolicy)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUpgradePolicy indicates an expected call of GetUpgradePolicy.
func (mr *MockOCMClientMockRecorder) GetUpgradePolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradePolicy", reflect.TypeOf((*MockOCMClient)(nil).GetUpgradePolicy), arg0, arg1)
}

// GetUpgradePolicyState mocks base method.
func (m *MockOCMClient) GetUpgradePolicyState(arg0, arg1 string) (*v1.UpgradePolicyState, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradePolicyState", arg0, arg1)
	ret0, _ := ret[0].(*v1.UpgradePolicyState)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUpgradePolicyState indicates an expected call of GetUpgradePolicyState.
func (mr *MockOCMClientMockRecorder) GetUpgradePolicyState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradePolicyState", reflect.TypeOf((*MockOCMClient)(nil).GetUpgradePolicyState), arg0, arg1)
}

// RemoveLimitedSupport mocks base method.
func (m *MockOCMClient) RemoveLimitedSupport(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLimitedSupport", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLimitedSupport indicates an expected call of RemoveLimitedSupport.
func (mr *MockOCMClientMockRecorder) RemoveLimitedSupport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLimitedSupport", reflect.TypeOf((*MockOCMClient)(nil).RemoveLimitedSupport), arg0, arg1)
}

// SendLimitedSupport mocks base method.
func (m *MockOCMClient) SendLimitedSupport(arg0 string, arg1 *v1.LimitedSupportReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLimitedSupport", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLimitedSupport indicates an expected call of SendLimitedSupport.
func (mr *MockOCMClientMockRecorder) SendLimitedSupport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLimitedSupport", reflect.TypeOf((*MockOCMClient)(nil).SendLimitedSupport), arg0, arg1)
}

// SendServiceLog mocks base method.
func (m *MockOCMClient) SendServiceLog(arg0 *v10.LogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendServiceLog", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendServiceLog indicates an expected call of SendServiceLog.
func (mr *MockOCMClientMockRecorder) SendServiceLog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendServiceLog", reflect.TypeOf((*MockOCMClient)(nil).SendServiceLog), arg0)
}

// UpdateUpgradePolicyState mocks base method.
func (m *MockOCMClient) UpdateUpgradePolicyState(arg0, arg1 string, arg2 *v1.UpgradePolicyState) (*v1.UpgradePolicyState, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUpgradePolicyState", arg0, arg1, arg2)
	ret0, _ := ret[0].(*v1.UpgradePolicyState)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateUpgradePolicyState indicates an expected call of UpdateUpgradePolicyState.
func (mr *MockOCMClientMockRecorder) UpdateUpgradePolicyState(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUpgradePolicyState", reflect.TypeOf((*MockOCMClient)(nil).UpdateUpgradePolicyState), arg0, arg1, arg2)
}
